apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: denyreg
webhooks:
  - name: registry-admission-service.default.svc.cluster.local
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      service:
        name: registry-admission-service
        namespace: default
        path: "/"
      caBundle: CA_BUNDLE
      
