apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: denyreg
webhooks:
  - name: registry-admission-service.default.svc.cluster.local
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      service:
        name: registry-admission-service
        namespace: default
        path: "/"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5RENDQXJDZ0F3SUJBZ0lSQU5NYVBSRDMrdVlwN2RpTVZ5SGxVQjB3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTVRrd016STRNVFV5T1RFMVdoY05NakV3TXpJM01UVXlPVEUxV2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBUGNJCmZnclNUZVQySTRmZDZQK0gvcHE3cHdneE1IRU0yamtYb1poNEpNWXExbmJqUUJPcEpzaG83clFEVnFLRzFzTVMKSHhBNVlwaUZaalZKa2t5eG9NSnNhOUEwTkd6czlrdERpVXc2OFA2VW01QXFKMFhPMFlLMWh6bEhKUzB0aExEVgpIZysxVXhWRGhVTTE1ZlpPbm5xYnNUTjRnZTlFMEtHalZsdzIzakR5RmZISG1wY1RxWkFsZ2RJNDQ5OWh2QzNuCmtZeW9NU0ZERjNabG13akRXOHpBeFFxK294cGlhSjNaZHVzTlRYQVdWdmNtaE80eFF3enZzNmpwaXl1ak5hNEwKV1UwNXExcVJGK2txUmIxTzVaU3YzNVl1bUlQRFlkRDBaVEJvWmcxU0JCOWxvZmc2L2l5ekIzZHNWSWVxOHRUbwpIQkJZMXZ1b3dLMVlJcDhDaE1CQlpoTkVsZXRlcXZDaTU5dnBYbys0SXhYN3RZN3IzekVpRUpjVk0vQ3NKSmhyCmJIS0w0N2NJcmkraG5iK0tLdVQxcktwNG9vNVBPL1NvcFZ1bnRNR2pXbzNNZkNEZFRITU9HVkQ2MmV0ejd4UUIKUzNFV2FLVFBUUnV0MDBZV0ZCclBZMVVvMnk0K2hxWjA2SG1Ra1BFV2JpZ1ZrM2hva2R6NEZEYW9MMStKV2hqegp2TlNXa1RKMzlXVTVRMWpBL29ydFhEUGFRcHZ6QkFvcVdMSGNoK1VFd1NxUyswR0ZxR0pRaVlZWXZBTHBmMlVsCjVxRCtZTXdTNVpOeEd5MHdZTllXOW02TTJjc3J2Z1BNcjFhZFBybmRSQmNJeWUvSjBLMDVKRnZmWnc4VlAwbmEKWE1DV2JlMHh6TmIzb00vMFlMTUVQdm95UUhaVXJ3cUtFMjZ5NU9lcEFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQytoaUN2CjJFbVJBUmFoREZFclZLVzZXdmMweGZOQlkxdFdta2JkQlB5dWhFK2hHdHVpaFpnV2pySUdoZlJCckc1NzJjV1gKSUtVcGtQYW5uWGpTTkk0d3RLY0ZBYmlGS2oyTjhlSkpncjZUMHFTTWVXeXhUcWtDbjRJTTh5cE1HV0pQQWJWMApveDlFU2E3dXh3eFN4N1V3S0VjeUN0cW1PZnFVQ20xMTFkdmdmeEpTOWZTTlc5MlNxZXJtZnhqYktqUmlWZjF6CmNFY3RTRFJOZW1mTGlpeDRGYURHSlJoOUlhTGhRcDg2OE1pbDRVOWlOaS8yNlFYWGxlVEdBcTlJakMvV25FME4KUVpBVXRJQ3Q5MDlHVlZSa3BaaXlHS3RsUE5Vd1FNdit6T0tqRnRtTVQ3dlI1OWhKL2R0VUQrdmE4YlFITTQ1SApYbUtyL3VGRWg5blNJSGtSUlh1WnVaL0ZSY3FsRDR4TDBxVUtVbmxkNzVYY25BMHh4SGIrSTdCT2NYL3NqQ3d2ClFTaENuSExRUTRMNWFvcU1UakhSdFkvc3hqUFdna25ZWmcxNE5lS0dCV2ZPOElkekNFOWtwUmc4NXJhMDFtQWgKNXQ2YkEwR2dIek9TRkU2OHk4QU1ZOHQyekZKV1phbyt6akdmTFdFb0d5ZlBla1RDb0VYbTk1eVUzQ3BVTGdiMQpxR2lYaEdqUVc0bjVFejM0VlBidGd0bjlrTVh6dnp2blczUVl3Rm5vQk5IeWp5cnNQdlFFbVhENGhCYlp2dzc5ClhjRWJqYm9pQnRWc0FjSGJzZE9XeFJoSytIb3o0a1FSenk3V0diVmVpWmIyM2RXS3NOZWlHQXV0SG5GaS80ZUgKd3JiNDdSUGRDdWFSV1dUQUlMd001dlV1anNwZVU5dkNkcFcwemc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
